In [2]:
import numpy as np

# Chapter 2: Linear Algebra (Continued)

## 2.6: Special Kinds of Matrices

### Diagonal Matrix

A matrix is __diagonal__ if it contains zero in all elements except along the main diagonal. I.e. all position except where $i = j$ are 0.  Note that a diagonal matrix does not need to be square.

In [29]:
# Creating a diagonal matrix in numPy:

a = np.zeros((5, 5), np.float16)
np.fill_diagonal(a, 1.8)
print(a)

[[1.8 0.  0.  0.  0. ]
 [0.  1.8 0.  0.  0. ]
 [0.  0.  1.8 0.  0. ]
 [0.  0.  0.  1.8 0. ]
 [0.  0.  0.  0.  1.8]]


In [30]:
# Another example
a = np.zeros((6, 10), np.int)

np.fill_diagonal(a, [-2, 4, 3, 55, 41, -4])
print(a)

[[-2  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 -4  0  0  0  0]]


In [31]:
# Another example using np.diag()

print(np.diag([-2, 4, 3, 55, 3, 4, 7, -12]))

[[ -2   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0]
 [  0   0   3   0   0   0   0   0]
 [  0   0   0  55   0   0   0   0]
 [  0   0   0   0   3   0   0   0]
 [  0   0   0   0   0   4   0   0]
 [  0   0   0   0   0   0   7   0]
 [  0   0   0   0   0   0   0 -12]]


Diagonal matrices are of interest because they are computationally efficient when used in multiplication.

$diag(v)$ denotes a square diagonal matrix whose diagonal is given by the vector $v$ - note that this corresponds to the numPy function name.

E.g. given $diag(v)x$, the result is just each element of $x_i$ by $v_i$. We can use numPy as an example of this special case:

In [53]:
# To demonstrate the equivalence, we can set up an example using numPy:

print("A square diagonal matrix diag([1, 2, 3, 4]):")
a = np.zeros((4, 4), np.float16)
np.fill_diagonal(a, [1, 2, 3, 4])
print(a)

print("---")

b = np.array([[1], [2], [3], [4]])
print(b)

print("---")
c_2 = np.dot(a, b)
print(c_2)

A square diagonal matrix diag([1, 2, 3, 4]):
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
---
[[1]
 [2]
 [3]
 [4]]
---
[[ 1.]
 [ 4.]
 [ 9.]
 [16.]]


It's also very easy to compute the inverse of a square diagonal matrix.

If a square diagonal has all-nonzero diagonal elements, the inverse is the diagonal matrix with one over each of the elements in the original; i.e.:

$$ \large diag(v)^{−1} = diag([1/v_1, \ldots ,1/v_n]^\top) $$

In [64]:
# Demonstrating this property using numPy:

print("A square diagonal matrix diag([1, 2, 2, 10, 8]):")
a = np.zeros((5, 5), np.float16)
np.fill_diagonal(a, [1, 2, 2, 10, 8])
print(a)

print("---")

print("A square diagonal matrix diag([1/1, 1/2, 1/2, 1/6, 1/8]):")
b = np.zeros((5, 5), np.float16)
np.fill_diagonal(b, [1/1, 1/2, 1/2, 1/10, 1/8])
print(b)

print("---")

print("Multiplying these gives the identity matrix):")
c = a.dot(b)
print(c)

A square diagonal matrix diag([1, 2, 2, 10, 8]):
[[ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  8.]]
---
A square diagonal matrix diag([1/1, 1/2, 1/2, 1/6, 1/8]):
[[1.    0.    0.    0.    0.   ]
 [0.    0.5   0.    0.    0.   ]
 [0.    0.    0.5   0.    0.   ]
 [0.    0.    0.    0.1   0.   ]
 [0.    0.    0.    0.    0.125]]
---
Multiplying these gives the identity matrix):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


The inverse does not exist for a diagonal matrix if any of the elements along the diagonal are zero.

### Symmetric Matrix

A __symmetric matrix__ is equal to its own transpose (and is relevant only for square matrices); i.e.:

$$ \large A = A^{\top} $$

In [68]:
a = np.array([[2, 16, 3], [16, -8, 1], [3, 1, -42]])
a_transpose = a.T

print(a)
print("---")
print(a_transpose)

[[  2  16   3]
 [ 16  -8   1]
 [  3   1 -42]]
---
[[  2  16   3]
 [ 16  -8   1]
 [  3   1 -42]]


### Unit Vector

__A unit vector__ has a length of 1.  In other words, it is a vector with __unit norm__.

$$ \Large \left\Vert x\right\Vert_2 = 1 $$

### Orthogonal Vectors

__Orthogonal vectors__ have a 90-degree angle relative to each other, and are vectors $x$ and $y$ where $x^\top y = 0$.

If orthogonal vectors are __orthogonal__ and have __unit norm__, they are said to be __orthonormal__.

### Orthogonal Matrices

An orthogonal matrix is a square matrix whose rows are mutually orthonormal and whose columns are mutually orthonormal. The inverse of an orthogonal matrix is cheap to compute due to its structure.

$$ \Large AA = AA^{\top} = I $$

This implies: 

$$ \Large A^{−1} = A^{\top} $$

In [95]:
from scipy.stats import ortho_group

x = ortho_group.rvs(4)

print(x)

print("---")

b = np.dot(x, x.T)

print(b)

print("---")

x_inv = np.linalg.inv(x)

x_T = x.T

print(x_inv)

print(x_T)

np.allclose(x_inv, x_T)

[[-0.50510599  0.26864664  0.72235747  0.38845413]
 [ 0.16286063  0.74461036 -0.42541806  0.48790502]
 [-0.64013477  0.38747638 -0.26456844 -0.60835276]
 [ 0.55549243  0.47248964  0.47667883 -0.49087575]]
---
[[ 1.00000000e+00 -2.44422054e-16 -1.75249628e-16  2.95552363e-16]
 [-2.44422054e-16  1.00000000e+00  2.74904615e-16  1.67722865e-16]
 [-1.75249628e-16  2.74904615e-16  1.00000000e+00 -7.39982285e-17]
 [ 2.95552363e-16  1.67722865e-16 -7.39982285e-17  1.00000000e+00]]
---
[[-0.50510599  0.16286063 -0.64013477  0.55549243]
 [ 0.26864664  0.74461036  0.38747638  0.47248964]
 [ 0.72235747 -0.42541806 -0.26456844  0.47667883]
 [ 0.38845413  0.48790502 -0.60835276 -0.49087575]]
[[-0.50510599  0.16286063 -0.64013477  0.55549243]
 [ 0.26864664  0.74461036  0.38747638  0.47248964]
 [ 0.72235747 -0.42541806 -0.26456844  0.47667883]
 [ 0.38845413  0.48790502 -0.60835276 -0.49087575]]


True

### Eigendecomposition

Eigendecomposition of matrices is the factorizing of matrices into its canonical form - it's representation as the product of its __eigenvalues__ and __eigenvectors__.

It's very useful to think of matrices as __linear transformations__.  We can think of "applying" matrices to a vector, resulting in some linear transformation of space - i.e. rotation and scaling, resulting in an output vector transformed in this way.  Applying a matrix is a way of saying we compute the dot product of the matrix with the initial vector to produce the output vector.

> An __eigenvector__ of of a square matrix $A$ is a nonzero vector $v$ such that multiplication by $A$ alters only the _scale_ of $v$.

$$ \Large Av = \lambda v $$

$\lambda$ is known as the __eigenvalue__ corresponding to this eigenvector.

In [98]:
# We can calculate the eigenvalues and right eigenvector of a matrix using numPy:

A = np.random.rand(2,2)

np.linalg.eig(A)

(array([0.00147145, 0.94827066]),
 array([[-0.99652227, -0.70442649],
        [ 0.08332685, -0.70977695]]))