In [1]:
import numpy as np
import pandas as pd

# Chapter 2: Linear Algebra

A branch of mathematics widely used throughout science and engineering.

Essential for understanding and working with machine learning algorithms.

## 2.1: Scalars, Vectors, Matrices and Tensors

- **Scalars**: A single number
- **Vectors**: An array of numbers; each number is identified by its index.
- **Matrices**: A 2D array of numbers; each number is identified by two indices
- **Tensors**: A general, variably-dimensional array of numbers;

### Scalars

We'll use NumPy throughout these notebooks.  Numpy defines a set of fundamental scalar types.

The default data type in numpy is `float_`.

In [2]:
"""
Some scalar numbers in Python
"""
x_1 = -0.000498
x_2 = 34

"""
NumPy defines 24 scalar types.  Note in cases such as bool_ and int_,
these are substantially different than the native Python counterparts.
"""

for t in np.ScalarType:
    print(t)

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'int'>
<class 'bool'>
<class 'bytes'>
<class 'str'>
<class 'memoryview'>
<class 'numpy.int8'>
<class 'numpy.uint8'>
<class 'numpy.float16'>
<class 'numpy.timedelta64'>
<class 'numpy.object_'>
<class 'numpy.int16'>
<class 'numpy.uint16'>
<class 'numpy.float32'>
<class 'numpy.complex64'>
<class 'numpy.bytes_'>
<class 'numpy.int32'>
<class 'numpy.uint32'>
<class 'numpy.float64'>
<class 'numpy.complex128'>
<class 'numpy.str_'>
<class 'numpy.int64'>
<class 'numpy.uint64'>
<class 'numpy.float128'>
<class 'numpy.complex256'>
<class 'numpy.bool_'>
<class 'numpy.void'>
<class 'numpy.longlong'>
<class 'numpy.ulonglong'>
<class 'numpy.datetime64'>


### Vectors

NumPy’s main object is the homogeneous multidimensional array.

We can represent a vector simply as a 1-dimensional array:

$\Large \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}$

In [3]:
# Let's represent a vector:
v_1 = np.array( [20, 30, 40, 50] )

print('Representing a vector of values:\n')
print(v_1)

print("---")
print(f'Shape: {v_1.shape}')
print(f'Dimensions: {v_1.ndim}')
print(f'Type: {type(v_1)}')
print(f'Type of values in matrix: {v_1.dtype}')

Representing a vector of values:

[20 30 40 50]
---
Shape: (4,)
Dimensions: 1
Type: <class 'numpy.ndarray'>
Type of values in matrix: int64


### Matrices

We can continue to use the same data structure (the `ndarray` type) to build matrices, or 2-dimensional  arrays:

$\Large \begin{bmatrix} A_{1,1} && A_{1,2} \\ A_{2,1} && A_{2,2} \end{bmatrix}$

In [4]:
# Let's create a few matrices with NumPy:

# An 8x8 matrix of ones of type int32
m_1 = np.ones((8, 8), dtype=np.int32)

print('Representing a matrix of 1s:\n')
print(m_1)

print("---")
print(f'Shape: {m_1.shape}')
print(f'Dimensions: {m_1.ndim}')
print(f'Type: {type(m_1)}')
print(f'Type of values in matrix: {m_1.dtype}')

Representing a matrix of 1s:

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
---
Shape: (8, 8)
Dimensions: 2
Type: <class 'numpy.ndarray'>
Type of values in matrix: int32


In [5]:
# A 2x6 matrix of random `float64s`
# we can do this with an instance of the default random number generator
rng = np.random.default_rng(1)
m_2 = rng.random((2, 6))

print('Representing a matrix of random float64s:\n')
print(m_2)

print("---")
print(f'Shape: {m_2.shape}')
print(f'Dimensions: {m_2.ndim}')
print(f'Type: {type(m_2)}')
print(f'Type of values in matrix: {m_2.dtype}')

Representing a matrix of random float64s:

[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]]
---
Shape: (2, 6)
Dimensions: 2
Type: <class 'numpy.ndarray'>
Type of values in matrix: float64


### Tensors

Given that __vectors__ are just first-order __tensors__, and __matrices__ are second-order __tensors__, we can continue to use the `ndarray` type to represent n-dimensional tensors:

In [6]:
# Let's make a 3-dimensional tensor!
t_1 = rng.random((3, 3, 3))

print('Representing a tensor:\n')
print(t_1)

print("---")
print(f'Shape: {t_1.shape}')
print(f'Dimensions: {t_1.ndim}')
print(f'Type: {type(t_1)}')
print(f'Type of values in tensor: {t_1.dtype}')

Representing a tensor:

[[[0.32973172 0.7884287  0.30319483]
  [0.45349789 0.1340417  0.40311299]
  [0.20345524 0.26231334 0.75036467]]

 [[0.28040876 0.48519097 0.9807372 ]
  [0.96165719 0.72478994 0.54122686]
  [0.2768912  0.16065201 0.96992541]]

 [[0.51606859 0.11586561 0.62348976]
  [0.77668311 0.6130033  0.9172977 ]
  [0.03959288 0.52858926 0.45933588]]]
---
Shape: (3, 3, 3)
Dimensions: 3
Type: <class 'numpy.ndarray'>
Type of values in tensor: float64


### Transpose Operation

> The transpose of a matrix is the mirror image of the matrix across a diagonal line, called the __main diagonal__, running down and to the right, starting from its upper left corner.

The __transpose__ of $A$ is denoted as $A^\top$.

$$\Huge (A^\top)_{i,j} = A_{j,i}$$

Notice in the illustration below how the transpose operation mirrors the matrix over the __main diagonal__:

$$\large A = \begin{bmatrix} A_{1,1} && A_{1,2} \\ A_{2,1} && A_{2,2} \\ A_{3,1} && A_{3,2} \end{bmatrix} \Rightarrow A^\top =  \begin{bmatrix} A_{1,1} && A_{2,1} && A_{3,1} \\ A_{1,2} && A_{2,2} && A_{3,2} \end{bmatrix} $$

If we consider __vectors__ to be special cases of __matrices__ with only a single column, then the __transpose__ of a vector is a matrix with a single row.

When writing a vector out in text (such as in a book), it's often practical to represent it as a transpose row, e.g:

$$\large [3.2, 2.1, 9.0, 4.8]^\top$$

The tranpose of a __scalar__ is just itself.

With NumPy, it's easy to compute the transpose of `ndarray` types:

### Transpose of a scalar in NumPy:

In [32]:
# Construct a scalar value of type float64
s_2 = np.float64(23.342)

s_2_transpose = s_2.transpose()

print(s_2, s_2.shape)
print(s_2_transpose, s_2.shape)

# Notice it's the same!

23.342 ()
23.342 ()


### Transpose of a vector in NumPy:

In [34]:
v_1_transpose = v_1.transpose()

print(v_1, v_1.shape)
print(v_1_transpose, v_1_transpose.shape)

# Notice it's the same, as far as NumPy is concerned!

[20 30 40 50] (4,)
[20 30 40 50] (4,)


### Transpose of a matrix in NumPy:

In [41]:
m_3 = np.random.randint(8, size=(2, 6))
m_3_transpose = m_3.transpose()

print("Original Matrix:")
print(m_3, m_3.shape)

print("Transposed Matrix:")
print(m_3_transpose, m_3_transpose.shape)

# Notice how the shape has changed!

Original Matrix:
[[1 1 4 2 3 5]
 [1 7 7 4 6 1]] (2, 6)
Transposed Matrix:
[[1 1]
 [1 7]
 [4 7]
 [2 4]
 [3 6]
 [5 1]] (6, 2)
